# Generated by Django 4.0.2 on 2022-05-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='over',
            field=models.BooleanField(default=False),
        ),
    ]
