# Generated by Django 4.0.2 on 2022-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0003_crash_result_state_crash_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='timer',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=4),
        ),
    ]
