# Generated by Django 4.0.2 on 2022-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0004_alter_crash_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashbets',
            name='stop_point',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
