# Generated by Django 4.0.2 on 2022-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0006_alter_crashbets_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashbets',
            name='stop_point',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
