# Generated by Django 4.0.2 on 2022-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0008_alter_crashbets_stop_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashbets',
            name='bet_choice',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
