# Generated by Django 4.0.2 on 2022-07-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0009_crashbets_bet_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crashbets',
            old_name='bet_time',
            new_name='created',
        ),
    ]
