# Generated by Django 4.0.2 on 2022-04-03 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposit', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_trade_link', models.CharField(max_length=128)),
                ('seller_api_key', models.CharField(default='', max_length=128)),
                ('asset_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=128)),
                ('item_wear', models.CharField(max_length=128)),
                ('market_hash_name', models.CharField(max_length=128)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=32)),
                ('icon_url', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offer_state', models.CharField(max_length=128)),
                ('buyer_id', models.CharField(max_length=17)),
                ('buyer_api_key', models.CharField(default='', max_length=128)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_skin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
