# Generated by Django 4.0.2 on 2022-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0005_depositeditems_buyer_trade_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositeditems',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
