# Generated by Django 4.0.2 on 2022-04-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0007_depositeditems_item_d_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositeditems',
            name='buyer_item_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
