# Generated by Django 4.0.2 on 2022-07-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0009_alter_depositeditems_buyer_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositeditems',
            name='item_skinline_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
