# Generated by Django 4.0.2 on 2022-07-20 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposit', '0011_alter_depositeditems_buyer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositeditems',
            name='buyer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_skin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
