# Generated by Django 4.0.2 on 2022-04-29 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseBattleSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_secret', models.CharField(max_length=32)),
                ('hashed_secret', models.CharField(max_length=64)),
                ('secret_generated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_1', models.IntegerField(default=0)),
                ('roll_2', models.IntegerField(default=0)),
                ('roll_3', models.IntegerField(default=0)),
                ('roll_4', models.IntegerField(default=0)),
                ('roll_5', models.IntegerField(default=0)),
                ('round_number', models.IntegerField(default=0, unique=True)),
                ('room_name', models.CharField(max_length=10)),
                ('battle_result', models.CharField(max_length=20)),
                ('battle_result_coins', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('battle_package', models.CharField(max_length=32)),
                ('battle_state', models.CharField(max_length=20)),
                ('battle_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
