# Generated by Django 4.0.2 on 2022-04-29 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casebattle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casebattle',
            old_name='battle_created',
            new_name='battle_joined',
        ),
        migrations.RemoveField(
            model_name='casebattle',
            name='battle_package',
        ),
        migrations.RemoveField(
            model_name='casebattle',
            name='battle_state',
        ),
        migrations.RemoveField(
            model_name='casebattle',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='casebattle',
            name='round_number',
        ),
        migrations.CreateModel(
            name='CaseBattleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=10)),
                ('round_number', models.IntegerField(default=0, unique=True)),
                ('battle_package', models.CharField(max_length=32)),
                ('battle_state', models.CharField(max_length=20)),
                ('room_created', models.DateTimeField(auto_now_add=True)),
                ('room_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_room_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='casebattle',
            name='room',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_room', to='casebattle.casebattleroom'),
            preserve_default=False,
        ),
    ]
