# Generated by Django 4.0.2 on 2022-04-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0002_rename_battle_created_casebattle_battle_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseBattlePackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='casebattleroom',
            name='battle_package',
        ),
        migrations.AddField(
            model_name='casebattleroom',
            name='package',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_package_name', to='casebattle.casebattlepackages'),
            preserve_default=False,
        ),
    ]
