# Generated by Django 4.0.2 on 2022-05-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0004_casebattleclientseed_casebattleserverseed_seeds_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seeds',
        ),
    ]
