# Generated by Django 4.0.2 on 2022-05-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0006_casebattle_used_client_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebattle',
            name='used_client_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_client_seed', to='casebattle.casebattleclientseed'),
        ),
    ]
