# Generated by Django 4.0.2 on 2022-05-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0007_alter_casebattle_used_client_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebattle',
            name='used_hashed_server_seed',
            field=models.CharField(default='asd', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casebattleserverseed',
            name='hashed_server_seed',
            field=models.CharField(default='xdsa', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casebattle',
            name='used_client_seed',
            field=models.CharField(blank=True, default='testc', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casebattle',
            name='used_server_seed',
            field=models.CharField(max_length=64),
        ),
    ]
