# Generated by Django 4.0.2 on 2022-05-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0008_casebattle_used_hashed_server_seed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseBattleChests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CaseBattleChestItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('item_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item_odds', models.DecimalField(decimal_places=10, max_digits=15)),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_chest', to='casebattle.casebattlechests')),
            ],
        ),
    ]
