# Generated by Django 4.0.2 on 2022-05-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0009_casebattlechests_casebattlechestitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebattlepackages',
            name='chest',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_packages_chest', to='casebattle.casebattlechests'),
            preserve_default=False,
        ),
    ]
