# Generated by Django 4.0.2 on 2022-05-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0012_alter_casebattle_roll_1_alter_casebattle_roll_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebattle',
            name='roll_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_rolled_item_1', to='casebattle.casebattlechestitems'),
        ),
        migrations.AlterField(
            model_name='casebattle',
            name='roll_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_rolled_item_2', to='casebattle.casebattlechestitems'),
        ),
        migrations.AlterField(
            model_name='casebattle',
            name='roll_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_rolled_item_3', to='casebattle.casebattlechestitems'),
        ),
        migrations.AlterField(
            model_name='casebattle',
            name='roll_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_rolled_item_4', to='casebattle.casebattlechestitems'),
        ),
        migrations.AlterField(
            model_name='casebattle',
            name='roll_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_rolled_item_5', to='casebattle.casebattlechestitems'),
        ),
    ]
