# Generated by Django 4.0.2 on 2022-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0019_casebattleroom_battle_result_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebattleroom',
            name='winner_count',
            field=models.IntegerField(default=0),
        ),
    ]
