# Generated by Django 4.0.2 on 2022-05-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0020_casebattleroom_winner_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casebattleserverseed',
            name='user',
        ),
    ]
