# Generated by Django 4.0.2 on 2022-07-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0021_remove_casebattleserverseed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebattlepackages',
            name='avatar',
            field=models.CharField(default='1', max_length=64),
        ),
    ]
