# Generated by Django 4.0.2 on 2022-07-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0022_casebattlepackages_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebattlepackages',
            name='avatar',
            field=models.CharField(default='images/1.svg', max_length=64),
        ),
    ]
