# Generated by Django 4.0.2 on 2022-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0023_alter_casebattlepackages_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebattlepackages',
            name='avatar',
            field=models.CharField(default='images/1.png', max_length=64),
        ),
    ]
