# Generated by Django 4.0.2 on 2022-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0023_alter_casebattlepackages_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebattlechestitems',
            name='exterior_name',
            field=models.CharField(default='test.com', max_length=128),
        ),
        migrations.AddField(
            model_name='casebattlechestitems',
            name='skinline_color',
            field=models.CharField(default='#4051F0', max_length=10),
        ),
        migrations.AddField(
            model_name='casebattlechestitems',
            name='skinline_name',
            field=models.CharField(default='Crimson Web', max_length=128),
        ),
        migrations.AddField(
            model_name='casebattlechestitems',
            name='url',
            field=models.CharField(default='test.com', max_length=256),
        ),
        migrations.AlterField(
            model_name='casebattlepackages',
            name='avatar',
            field=models.CharField(default='images/1.png', max_length=64),
        ),
    ]
