# Generated by Django 4.0.2 on 2022-07-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0024_casebattlechestitems_exterior_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebattlechestitems',
            name='url',
            field=models.CharField(default='test.com', max_length=512),
        ),
    ]
