# Generated by Django 4.0.2 on 2022-07-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0024_alter_casebattlepackages_avatar'),
        ('casebattle', '0025_alter_casebattlechestitems_url'),
    ]

    operations = [
    ]
