# Generated by Django 4.0.2 on 2022-07-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0029_remove_casebattle_used_hashed_server_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebattleroom',
            name='used_server_seed',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='casebattle_used_server_seed', to='casebattle.casebattleserverseed'),
        ),
    ]
