# Generated by Django 4.0.2 on 2022-07-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casebattle', '0031_alter_casebattleroom_used_server_seed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseBattleClientSeed',
        ),
    ]
