# Generated by Django 4.0.2 on 2022-04-01 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_value_crypto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('crypto_type', models.CharField(max_length=10)),
                ('transaction_value_gold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('steam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
