# Generated by Django 4.0.2 on 2022-04-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0002_withdraw_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_value_crypto',
            field=models.DecimalField(decimal_places=10, max_digits=16),
        ),
    ]
