# Generated by Django 4.0.2 on 2022-05-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_roulette_roulettepublicseeds_rouletteserverseeds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettebets',
            name='win',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
