# Generated by Django 4.0.2 on 2022-05-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_roulettebets_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulettebets',
            name='bet_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
