# Generated by Django 4.0.2 on 2022-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_roulettebets_bet_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettebets',
            name='win_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
