# Generated by Django 4.0.2 on 2022-07-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_roulettebets_win_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trade_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
