# Generated by Django 4.0.2 on 2022-07-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser_trade_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roulettebets',
            old_name='bet_time',
            new_name='created',
        ),
    ]
