# Generated by Django 4.0.2 on 2022-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_roulettebets_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_seed',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
